
--SELECT COUNT(*) FROm ADMINUSER;
--SELECT COUNT(*) FROm ACCOUNT;
--SELECT COUNT(*) FROm USERDETAILS;

CREATE TABLE ADMINUSER
(
username VARCHAR2(50),
firstname VARCHAR2(50),
lastname VARCHAR2(50),
dateofbirth  TIMESTAMP,
gender VARCHAR2(10),
isEnabled VARCHAR2(1),
isLocked VARCHAR2(1),
createdate  TIMESTAMP,
updateddate TIMESTAMP
);
ALTER TABLE ADMINUSER ADD CONSTRAINT PK_ADMINUSER PRIMARY KEY (username);

CREATE TABLE ACCOUNT
(
accountid NUMBER(10,0),
username  VARCHAR2(50),
accounttype  VARCHAR2(10),
branchcode  VARCHAR2(10),
isactive  VARCHAR2(10),
currency  VARCHAR2(10),
opendate   TIMESTAMP,
closeddate TIMESTAMP
);

CREATE SEQUENCE ACCOUNT_ACCOUNTNO_SEQ START WITH 1000 INCREMENT BY 1;

ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (accountid);
ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_USERNAME FOREIGN KEY (username) REFERENCES ADMINUSER(username);


CREATE TABLE USERDETAILS
(
username VARCHAR2(50),
userpwd VARCHAR2(50),
userrole VARCHAR2(50),
usertype VARCHAR2(50),
theme VARCHAR2(50),
userlang VARCHAR2(50),
email VARCHAR2(50),
mobile VARCHAR2(50),
updateddate TIMESTAMP
);

ALTER TABLE USERDETAILS ADD CONSTRAINT PK_USERDETAILS PRIMARY KEY (username);
ALTER TABLE USERDETAILS ADD CONSTRAINT FK_USERDETAILS_USERNAME FOREIGN KEY (username) REFERENCES ADMINUSER(username);


